-- Autogenerated lua file by the Spyface tool
-- 'Wimps and posers -- leave the hall! -- ManOwaR
--
-- DO NOT HAND EDIT.
--
dependents =
{
}
text_styles =
{
}
skins =
{
}
widgets =
{
    {
        name = [[Group]],
        isVisible = true,
        noInput = false,
        anchor = 5,
        rotation = 0,
        x = 90,
        y = 146,
        w = 0,
        h = 0,
        sx = 1,
        sy = 1,
        ctor = [[group]],
        children =
        {
            {
                name = [[progressbar]],
                isVisible = true,
                noInput = false,
                anchor = 1,
                rotation = 0,
                x = -1,
                xpx = true,
                y = -6,
                ypx = true,
                w = 130,
                wpx = true,
                h = 130,
                hpx = true,
                sx = 1,
                sy = 1,
                ctor = [[discprogressbar]],
            },
        },
    },
}
transitions =
{
}
properties =
{
    sinksInput = true,
}
return {
    dependents = dependents,
    text_styles = text_styles,
    transitions = transitions,
    skins = skins,
    widgets = widgets,
    properties =
        properties,
    currentSkin = nil
}
